version: '3.8'

services:
  ginol-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    env_file:
      - .env         
    depends_on:
      - db          
    restart: always 

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ginol_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
